# .gitpod.yml
tasks:
  - init: |
      npm install
      npm install wagmi ethers@^5.7.0 @wagmi/connectors tailwindcss postcss autoprefixer gh-pages
      npx tailwindcss init -p
    command: |
      npm start
ports:
  - port: 3000
    onOpen: open-preview
